version: '3'
services:
  php-cli:
    container_name: docker-blueprint-php-cli
    image: docker-blueprint-php-cli
    build: .
    user: www-data
    entrypoint: bash
    working_dir: /usr/src/app
    volumes:
      - ../../:/usr/src/app
      - ./cache/composer:/composer/cache/
      - ./logs/.bash_history:/home/www-data/.bash_history
      - ./configs/.bashrc:/home/www-data/.bashrc
      - ./configs/php.ini:/usr/local/etc/php/php.ini
      - ~/.ssh/:/home/www-data/.ssh
    networks:
      - docker-blueprint-network
networks:
  docker-blueprint-network:
    external:
      name: docker-blueprint-network